
CREATE TABLE SRC.ORDER_LINE
(
  ORDER_ID       NUMBER,
  ORDER_LINE_ID  NUMBER,
  PRODUCT_ID     NUMBER,
  QUANTITY       NUMBER,
  PRICE          INTEGER,
  CREATION_DATE  DATE                           DEFAULT SYSDATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, 
--     QUANTITY, PRICE, CREATION_DATE
--  FROM SRC.ORDER_LINE;
--
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (2, 1, 5, 1, 50000, 
    TO_DATE('01/14/2016 19:55:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (2, 2, 3, 1, 30000, 
    TO_DATE('01/14/2016 19:55:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (2, 3, 6, 1, 15000, 
    TO_DATE('01/14/2016 19:55:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (1, 1, 1, 1, 30000, 
    TO_DATE('01/13/2016 23:06:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (1, 2, 3, 1, 20000, 
    TO_DATE('01/13/2016 23:06:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.ORDER_LINE
   (ORDER_ID, ORDER_LINE_ID, PRODUCT_ID, QUANTITY, PRICE, 
    CREATION_DATE)
 Values
   (1, 3, 5, 1, 50000, 
    TO_DATE('01/13/2016 23:06:24', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;





CREATE TABLE SRC.PRODUCT
(
  PRODUCT_ID        INTEGER,
  PRODUCT_NAME      VARCHAR2(45 BYTE),
  PRODUCT_DESC      VARCHAR2(100 BYTE),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index SRC.SYS_C0012842.
--  The object is created when the parent object is created.

ALTER TABLE SRC.PRODUCT ADD (
  PRIMARY KEY
  (PRODUCT_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);





SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, 
--     CREATION_DATE, LAST_UPDATE_DATE
--  FROM SRC.PRODUCT;
--
Insert into SRC.PRODUCT
   (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, CREATION_DATE, LAST_UPDATE_DATE)
 Values
   (1, 'XBOX ONE', 'GAME CONSOLE', TO_DATE('01/13/2016 12:54:27', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/13/2016 12:54:27', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.PRODUCT
   (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, CREATION_DATE, LAST_UPDATE_DATE)
 Values
   (2, 'PS 4', 'GAME CONSOLE', TO_DATE('01/13/2016 12:54:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/13/2016 12:54:46', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.PRODUCT
   (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, CREATION_DATE, LAST_UPDATE_DATE)
 Values
   (3, 'MOTO 360', 'WEARABLE', TO_DATE('01/13/2016 12:55:14', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/13/2016 12:55:14', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.PRODUCT
   (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, CREATION_DATE, LAST_UPDATE_DATE)
 Values
   (4, 'NEXUS', 'TABLET FROM NEXUS', TO_DATE('01/13/2016 12:55:34', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/13/2016 12:55:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into SRC.PRODUCT
   (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESC, CREATION_DATE, LAST_UPDATE_DATE)
 Values
   (5, 'IPHONE 6', 'PHONE', TO_DATE('01/14/2016 19:55:23', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/14/2016 19:55:23', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;









